//
//  FyberAdProvider.m
//  GSG
//
//  Created by Robert Segal on 2014-09-29.
//  Copyright (c) 2014 Get Set Games. All rights reserved.
//

#import "FyberAdProvider.h"
#import "GSGAdManager.h"
//#import "GSGAudioEngine.h"
//#import "OFInventory.h"

@interface FyberAdProvider()
@property (nonatomic, readwrite, retain) NSMutableDictionary *requests;
@end

@implementation FyberAdProvider

-(id)init
{
    self = [super init];
    
    if (self)
    {
        self.requests = [NSMutableDictionary dictionaryWithCapacity:1];
    }
    
    return self;
}

-(void)dealloc
{
    self.client   = nil;
    self.requests = nil;
    
    [super dealloc];
}

-(void)initialize
{
    static NSString *token = @"";
    
    if (token.length == 0)
    {
        token = [[SponsorPaySDK startWithAutogeneratedUserForAppId:@"25943"
                                                     securityToken:@"76063af474ced17cc1f52851c4ea586f"] retain];
    }
}

-(void)cacheAd
{
    self.client = [SponsorPaySDK requestBrandEngageOffersNotifyingDelegate:self];
    self.requests[[FyberAdProvider addressAsString:self.client]] = self.delegate;
    
    ((SPBrandEngageClient *)self.client).shouldShowRewardNotificationOnEngagementCompleted = NO;
    [SponsorPaySDK setShowPayoffNotificationOnVirtualCoinsReceived:NO];
}

-(BOOL)hasCachedAd
{
    return self.areOffersAvailable;
}


-(BOOL)showAd
{
    self.requests[[FyberAdProvider addressAsString:self.client]] = self.delegate;
    
    return [self.client startWithParentViewController:self.viewController];
}

- (void)virtualCurrencyConnector:(SPVirtualCurrencyServerConnector *)connector
  didReceiveDeltaOfCoinsResponse:(double)deltaOfCoins
                    currencyName:(NSString *)currencyName
             latestTransactionId:(NSString *)transactionId
{
//    [OFInventory modifyCurrency:[NSString stringWithFormat:@"%@.mp", [NSBundle mainBundle].bundleIdentifier]
//                         amount:[[NSNumber numberWithDouble:deltaOfCoins] integerValue]];
    
    [[NSNotificationCenter defaultCenter] postNotificationName:kAdProviderAwardVirtualCurrencyRewardNotification
                                                        object:nil
                                                      userInfo:@{ @"delta" : [NSNumber numberWithDouble:deltaOfCoins] }];
}

-(void)virtualCurrencyConnector:(SPVirtualCurrencyServerConnector *)vcConnector
                failedWithError:(SPVirtualCurrencyRequestErrorType)error
                      errorCode:(NSString *)errorCode
                   errorMessage:(NSString *)errorMessage
{
   
/*
    NO_ERROR,
    ERROR_NO_INTERNET_CONNECTION,
    ERROR_INVALID_RESPONSE,
    ERROR_INVALID_RESPONSE_SIGNATURE,
    SERVER_RETURNED_ERROR,
    ERROR_OTHER*/
}

- (void)brandEngageClient:(SPBrandEngageClient *)brandEngageClient
         didReceiveOffers:(BOOL)areOffersAvailable
{
    if (areOffersAvailable)
    {
        self.areOffersAvailable = areOffersAvailable;
    }
    
    NSObject *d = self.requests[[FyberAdProvider addressAsString:brandEngageClient]];
    
    if (d)
    {
        [FyberAdProvider safeTargetPerformSelector:d
                                          selector:@selector(adProviderDidCacheAd:)
                                        withObject:@{ @"areOffersAvailable" : [NSNumber numberWithBool:self.areOffersAvailable] }];
    }
}

- (void)brandEngageClient:(SPBrandEngageClient *)brandEngageClient
          didChangeStatus:(SPBrandEngageClientStatus)newStatus
{
    NSString *clientHash = [FyberAdProvider addressAsString:brandEngageClient];
    NSObject *d          = self.requests[clientHash];
    
    BOOL completed      = NO;
    BOOL completedOffer = NO;
    
    switch (newStatus) {
        case CLOSE_FINISHED:
            
            dispatch_async(dispatch_get_main_queue(), ^{
                
                // Fyber suggest waiting 3 seconds after CLOSE_FINISHED has been received from an engagement
                // before requesting currency.
                //
                // http://developer.fyber.com/content/ios/basics/rewarding-the-user/vcs/
                //
                static NSTimeInterval kFyberRequestForCoinsWaitTime = 3.0;
                
                [SponsorPaySDK performSelector:@selector(requestDeltaOfCoinsNotifyingDelegate:) withObject:self afterDelay:kFyberRequestForCoinsWaitTime];
            });

            completedOffer = YES;
            completed      = YES;
            break;
            
        case CLOSE_ABORTED:
        case ERROR:
            completedOffer = NO;
            completed      = YES;
            break;
            
        case STARTED:
        {
            [GSGAdManager sharedInstance].adInProgress = YES;
            
           // [[GSGAudioEngine sharedEngine] stopBackgroundMusic];
            
            [FyberAdProvider safeTargetPerformSelector:d
                                              selector:@selector(adProviderShowAd:)
                                            withObject:@{ @"status" : [NSNumber numberWithInt:newStatus] }];
            
            break;
        }
            
        default:
            break;
    }
    
    if (completed)
    {
        self.areOffersAvailable = NO;
        [GSGAdManager sharedInstance].adInProgress = NO;
        
       // [[GSGAudioEngine sharedEngine] safeResumeBackgroundMusic];
        
        if (d)
        {
            [FyberAdProvider safeTargetPerformSelector:d
                                              selector:@selector(adProviderIsHidden:)
                                            withObject:@{ @"wasOfferCompleted" : [NSNumber numberWithBool:completedOffer],
                                                          @"status"            : [NSNumber numberWithInt:newStatus] }];
        }
        
        [self.requests removeObjectForKey:clientHash];
    }
}

-(void)flush
{
    // Flush out any coins that may be sitting on the server.  Used only on first run
    // cases so users can't double dip on rewards.
    //
    [SponsorPaySDK requestDeltaOfCoinsNotifyingDelegate:nil];
}

-(void)clearRequests
{
    // Clear out any active requests which may be running effectively cancelling anything that is running.
    //
    [self.requests removeAllObjects];
}

+(NSString *)addressAsString:(NSObject *)obj
{
    return obj ? [NSString stringWithFormat:@"%p", obj] : @"";
}

+(void)safeTargetPerformSelector:(NSObject *)target selector:(SEL)s withObject:(NSObject *)obj
{
    if (target)
    {
        if ( [target respondsToSelector:s] )
        {
            [target performSelector:s withObject:obj ? obj : nil];
        }
    }
}

@end
